name: ebankapp
description: ebank.ie main website

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  bootstrap_sass: any

dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers: ^0.4.0
  sass_builder: ^2.1.2

targets:
  $default:
    builders:
      sass_builder:
        options:
          outputStyle: compressed